/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST"
 * 	found in "/home/fu/asn1cpp/test/common/asn/definitions.asn"
 * 	`asn1c -fwide-types -gen-PER`
 */

#ifndef	_TestInteger_H_
#define	_TestInteger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestInteger */
typedef struct TestInteger {
	INTEGER_t	 integer;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestInteger_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestInteger;

#ifdef __cplusplus
}
#endif

#endif	/* _TestInteger_H_ */
#include <asn_internal.h>
