/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST"
 * 	found in "/home/fu/asn1cpp/test/common/asn/definitions.asn"
 * 	`asn1c -fwide-types -gen-PER`
 */

#include "TestOptional.h"

static asn_TYPE_member_t asn_MBR_sequence_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_sequence_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sequence_specs_5 = {
	sizeof(struct sequence),
	offsetof(struct sequence, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sequence_5 = {
	"sequence",
	"sequence",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sequence_tags_5,
	sizeof(asn_DEF_sequence_tags_5)
		/sizeof(asn_DEF_sequence_tags_5[0]) - 1, /* 1 */
	asn_DEF_sequence_tags_5,	/* Same as above */
	sizeof(asn_DEF_sequence_tags_5)
		/sizeof(asn_DEF_sequence_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_sequence_5,
	1,	/* Single element */
	&asn_SPC_sequence_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_nested_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TestInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_nested_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_nested_specs_7 = {
	sizeof(struct nested),
	offsetof(struct nested, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nested_7 = {
	"nested",
	"nested",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nested_tags_7,
	sizeof(asn_DEF_nested_tags_7)
		/sizeof(asn_DEF_nested_tags_7[0]) - 1, /* 1 */
	asn_DEF_nested_tags_7,	/* Same as above */
	sizeof(asn_DEF_nested_tags_7)
		/sizeof(asn_DEF_nested_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_nested_7,
	1,	/* Single element */
	&asn_SPC_nested_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_TestOptional_1[] = {
	{ ATF_POINTER, 5, offsetof(struct TestOptional, integer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"integer"
		},
	{ ATF_POINTER, 4, offsetof(struct TestOptional, string),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"string"
		},
	{ ATF_POINTER, 3, offsetof(struct TestOptional, boolean),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"boolean"
		},
	{ ATF_POINTER, 2, offsetof(struct TestOptional, sequence),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_sequence_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sequence"
		},
	{ ATF_POINTER, 1, offsetof(struct TestOptional, nested),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_nested_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nested"
		},
};
static const int asn_MAP_TestOptional_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_TestOptional_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TestOptional_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* string */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* boolean */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sequence */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* nested */
};
static asn_SEQUENCE_specifics_t asn_SPC_TestOptional_specs_1 = {
	sizeof(struct TestOptional),
	offsetof(struct TestOptional, _asn_ctx),
	asn_MAP_TestOptional_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_TestOptional_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TestOptional = {
	"TestOptional",
	"TestOptional",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TestOptional_tags_1,
	sizeof(asn_DEF_TestOptional_tags_1)
		/sizeof(asn_DEF_TestOptional_tags_1[0]), /* 1 */
	asn_DEF_TestOptional_tags_1,	/* Same as above */
	sizeof(asn_DEF_TestOptional_tags_1)
		/sizeof(asn_DEF_TestOptional_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TestOptional_1,
	5,	/* Elements count */
	&asn_SPC_TestOptional_specs_1	/* Additional specs */
};

