/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST"
 * 	found in "/home/fu/asn1cpp/test/common/asn/definitions.asn"
 * 	`asn1c -fwide-types -gen-PER`
 */

#ifndef	_TestSetOf_H_
#define	_TestSetOf_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <PrintableString.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TestInteger;

/* TestSetOf */
typedef struct TestSetOf {
	struct integer {
		A_SET_OF(INTEGER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} integer;
	struct string {
		A_SET_OF(PrintableString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} string;
	struct boolean {
		A_SET_OF(BOOLEAN_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} boolean;
	struct nested {
		A_SET_OF(struct TestInteger) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nested;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestSetOf_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestSetOf;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TestInteger.h"

#endif	/* _TestSetOf_H_ */
#include <asn_internal.h>
