/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST"
 * 	found in "/home/fu/asn1cpp/test/common/asn/definitions.asn"
 * 	`asn1c -fwide-types -gen-PER`
 */

#ifndef	_TestNested_H_
#define	_TestNested_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TestInteger.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestNested */
typedef struct TestNested {
	TestInteger_t	 nested;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestNested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestNested;

#ifdef __cplusplus
}
#endif

#endif	/* _TestNested_H_ */
#include <asn_internal.h>
