/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VehClass"
 * 	found in "/home/fu/asn1cpp/test/common/asn/VehClass.asn"
 * 	`asn1c -fwide-types -gen-PER`
 */

#ifndef	_VehicleClassification_H_
#define	_VehicleClassification_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BasicVehicleClass.h"
#include "FuelType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleClassification */
typedef struct VehicleClassification {
	BasicVehicleClass_t	 classification;
	FuelType_t	*fuelType	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleClassification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleClassification;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleClassification_H_ */
#include <asn_internal.h>
